### ISSUE TITLE
Current include statements are not compatible with GCC

### ISSUE THREAD

**Issue by 4re** [kewenyu/VapourSynth-BezierCurve#1]
https://github.com/kewenyu/VapourSynth-BezierCurve/blob/0ac2c62213484b34857edd67ee1bca13b67e6a7b/VapourSynth-BezierCurve/BezierCurve.h#L4-L5

Can you change the backslashes to forward slashes in the include statements? As far as I know this is not "legal" and may produce an undefined behavior in many compilers. By that matter, GCC errors out at those lines.

If that is not compatible with MSCC you could just eliminate the `vapoursynth\` part from the include statements and let the user pass the appropriate search path to the compiler.

Also I can provide a build system (it would be just one file in the root of the repo) for non-windows systems if it is OK with you.

EDIT: https://stackoverflow.com/questions/29119638/why-path-in-vs-c-contains-forward-slash-not-backslash

**Comment by kewenyu** [comment]
> you could just eliminate the vapoursynth\ part from the include statements

Fixed it.

> Also I can provide a build system (it would be just one file in the root of the repo) for non-windows systems if it is OK with you.

I would appreciate it if you could provide it.

**Comment by 4re** [comment]
Thanks
